-- MySQL Script generated by MySQL Workbench
-- 10/01/17 15:55:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database` DEFAULT CHARACTER SET utf8 ;
USE `database` ;

-- -----------------------------------------------------
-- Table `database`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`funcionario` (
  `idfunc` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  `salario` DOUBLE(12,2) NOT NULL COMMENT '',
  `sexo` CHAR(1) NOT NULL COMMENT '',
  `cpf` DOUBLE(11,0) NOT NULL COMMENT '',
  PRIMARY KEY (`idfunc`)  COMMENT '',
  UNIQUE INDEX `cpf` (`cpf` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;

USE `database` ;

-- -----------------------------------------------------
-- procedure DELETELINE
-- -----------------------------------------------------

DELIMITER $$
USE `database`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `DELETELINE`(IN V_IDFUNC INT, OUT resposta VARCHAR(50))
SALVAR:BEGIN
		DECLARE excecao SMALLINT DEFAULT 0;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET excecao = 1;
		START TRANSACTION;
				DELETE FROM FUNCIONARIO WHERE idfunc = V_IDFUNC;
		IF excecao = 1 THEN
				SET resposta = 'Erro ao deletar dados';
				ROLLBACK;
				LEAVE SALVAR;
		ELSE
				SET resposta = 'Deletado com sucesso!';
				COMMIT;
		END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure INSERTTAB
-- -----------------------------------------------------

DELIMITER $$
USE `database`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERTTAB`(IN V_NOME VARCHAR(100), IN V_SALARIO DOUBLE, IN V_SEXO CHAR, IN V_CPF DOUBLE, OUT RESPOSTA VARCHAR(50))
SALVAR:BEGIN
		DECLARE excecao SMALLINT DEFAULT 0;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET excecao = 1;
		START TRANSACTION;
				INSERT INTO FUNCIONARIO(NOME, SALARIO, SEXO, CPF) VALUES (V_NOME, V_SALARIO, V_SEXO, V_CPF);
		IF excecao = 1 THEN
				SET RESPOSTA = 'Erro ao gravar dados';
				ROLLBACK;
				LEAVE SALVAR;
		ELSE
				SET RESPOSTA = 'Salvo com sucesso!';
				COMMIT;
		END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure RETURNSAL
-- -----------------------------------------------------

DELIMITER $$
USE `database`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `RETURNSAL`(IN V_ID INT, OUT V_SALARIO DOUBLE)
SALVAR:BEGIN
	DECLARE excecao SMALLINT DEFAULT 0;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET excecao = 1;
		START TRANSACTION;
			SELECT SALARIO INTO V_SALARIO FROM funcionario WHERE IDFUNC=V_ID;
		IF excecao = 1 THEN
				SET V_SALARIO = 1;
				ROLLBACK;
				LEAVE SALVAR;
		END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure SELECTTAB
-- -----------------------------------------------------

DELIMITER $$
USE `database`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SELECTTAB`(IN V_ID INT, OUT resposta VARCHAR(50), OUT V_NOME VARCHAR(100), OUT V_SALARIO DOUBLE)
SALVAR:BEGIN
		DECLARE excecao SMALLINT DEFAULT 0;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET excecao = 1;
		START TRANSACTION;
				SELECT SALARIO INTO V_SALARIO FROM funcionario WHERE IDFUNC = V_ID;
				SELECT NOME INTO V_NOME FROM funcionario WHERE IDFUNC = V_ID;

		IF excecao = 1 THEN
				SET resposta = 'Erro ao buscar dados';
				ROLLBACK;
				LEAVE SALVAR;
		ELSE
				SET resposta = 'Dados trazidos com sucesso!';
				COMMIT;
		END IF;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
